### ISSUE TITLE
Move to plain HTTP library to avoid quirks in jsonrpc-client

### ISSUE THREAD

**Issue by xxuejie** [ckb-js/lumos#6]
Right now lumos indexer uses JSONRPC client library as used in [ckb-indexer](https://github.com/quake/ckb-indexer/blob/master/Cargo.toml#L13-L14). But one problem with this library, is that it is [hardcoded](https://github.com/paritytech/jsonrpc/blob/1779dbef95dd5189d73516782e861661b463cd3d/core-client/transports/src/transports/http.rs#L104-L107) with `hyper::rt`, which makes it impossible to swap runtime. To make matters worse, `hyper::rt` uses a tokio in a mode that forbids running on a single core machine.

Since we only need JSONRPC for one API, it won't be a problem for us to build the specific code we need on a plain HTTP library, which would has better async/await support, such as [surf](https://github.com/http-rs/surf).

**Comment by homura** [comment]
Lumos doesn't the support native indexer anymore, so we can close this issue
